### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by railken** [GregTechCE/GregTech#142]
After upgrading to 1.12.2-0.4.2.5 available on curseforge

The crash seems to appear randomly when moving

### Client error:
Internal server Error

### Server error:

```net.minecraft.util.ReportedException: Ticking player
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zik000(NetHandlerPlayServer.java:2035) ~[pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/color/BlockColors
        at gregtech.common.blocks.BlockSurfaceRock.func_149645_b(BlockSurfaceRock.java:170) ~[BlockSurfaceRock.class:?]
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185901_i(BlockStateContainer.java:356) ~[awu$a.class:?]
        at net.minecraft.entity.Entity.func_174808_Z(Entity.java:1275) ~[vg.class:?]
        at net.minecraft.entity.Entity.func_174830_Y(Entity.java:1262) ~[vg.class:?]
        at net.minecraft.entity.Entity.func_70030_z(Entity.java:465) ~[vg.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:224) ~[vp.class:?]
        at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388) ~[vg.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2087) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
        ... 10 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.color.BlockColors
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
        at gregtech.common.blocks.BlockSurfaceRock.func_149645_b(BlockSurfaceRock.java:170) ~[BlockSurfaceRock.class:?]
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185901_i(BlockStateContainer.java:356) ~[awu$a.class:?]
        at net.minecraft.entity.Entity.func_174808_Z(Entity.java:1275) ~[vg.class:?]
        at net.minecraft.entity.Entity.func_174830_Y(Entity.java:1262) ~[vg.class:?]
        at net.minecraft.entity.Entity.func_70030_z(Entity.java:465) ~[vg.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:224) ~[vp.class:?]
        at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388) ~[vg.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2087) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
        ... 10 more
```

**Comment by Archengius** [comment]
fixed in dev

**Comment by railken** [comment]
Thanks!

Do you have an estimation of when a new build will be released? The bug is quite frustrating
